script: bash ./deploy.sh
language: node_js
node_js:
  - '0.12'
env:
  global:
  - GH_REF: github.com/mushishi78/amp-generator.git
  - secure: VoOY8btGJUD5q35NlUl0XG5tHMtG2UWVw1e9dKOdZTu8ICOWw/VSlU1UkF4+wPk17NYihuy7+NpCkDqNZXSC91mKdUWZV65eqzN1MakT6XmX2QqBotdBCp1gnwxYe+4ZSdN5AaCYxBTGBgC/AVCaNo3P0JDXj1VXMI4F1cR5CZ2CmwLEMWGGNRtysr12UK2RC5q5wl2LqqVv3TqP4q8tlyh2GQ6GfBf6s3iVekPxPannb5WZDX0B2TmueI4rPfxo0ptNutoyi6fS82y7pNqNEec4Mci0QekQp+6fvVNpeLJQCP8ilp55cntS43z4CZTIB1gboz9lHwGC3bYie8PizlgYOeZ/wGMJcQZWJf3uppr+coxuk6scKfdcyWPwGEuwGkFX8mIC25qHBerm3ncBqyTNbi8xHF6jcYs8siTTA90NonFBbGWDe3pzEDg5hLKRBpMkfnuk6A//KrUCFn4JtTcnz625lx5SV14fF8Yw5LW1I2Arfd+qw6Ojw5bi7PquXVrtGIUhgV6JVV66AgOyRxIICk3E3o4ZU8Sh/nYdd8AlqrBsH7bKc0mpWI2NVwqid9fR4FY6VD9vpyq2LPHtfcHUn2tmMLjU3ODBl/PrDHsukmhlpcb269VGvoKeQEFXdwZSXk1ZTMS6quYuY94nYqtghfePIg7lgN98HoMur/8=
